apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swaroop-ingress
  namespace: swaroop
  labels:
    app: swaroop-formulation
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - swaroop.in
      secretName: swaroop-tls
  rules:
    - host: swaroop.in
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: swaroop-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: swaroop-frontend
                port:
                  number: 80
