frontend:
  replicaCount: 2
  image:
    repository: swaroop/frontend
    tag: latest

backend:
  replicaCount: 2
  image:
    repository: swaroop/backend
    tag: latest

postgres:
  enabled: true
  storage: 5Gi

redis:
  enabled: true

ingress:
  enabled: true
  host: swaroop.in

monitoring:
  enabled: true
